name: tsharp
description: A programming language in dart.
version: 1.0.0
author: Tony Borchert
homepage:

dependencies:
  meta: any

dev_dependencies:
  test: ^1.16.8

environment:
  sdk: ">=2.12.2 <3.0.0"
