name: tsharp
description: A scripting language written in dart.
version: 1.0.0
author: Tony Borchert
homepage: https://github.com/bit-burger/tsharp

dependencies:
  meta: any
  woozy_search:
    git:
      url: https://github.com/bit-burger/woozy-search.git
      ref: easy_access_matchresult2

dev_dependencies:
  test: ^1.16.8

environment:
  sdk: ">=2.12.2 <3.0.0"
